#!/usr/bin/env python3
"""
validate_semenov_table.py

Validate the dense Semenov Rosseland opacity table generated by
generate_semenov_table.py.

The validation compares:

    kappa_direct(rho, T)

computed from the Python reproduction of the original Semenov COP/gop logic,

against:

    kappa_interp(rho, T)

obtained by bilinear interpolation of the dense table in

    (log10 rho, log10 T, log10 kappa_R).

The test uses random off-grid points plus targeted samples around the main
opacity-transition temperatures.

Default validation domain is chosen for the current PDS 70 application:

    -16 <= log10(rho / g cm^-3) <= -11
    5 K <= T <= 1e4 K

All opacities are in cm^2 g^-1.
"""

import argparse
from pathlib import Path
import importlib.util

import numpy as np
import matplotlib.pyplot as plt


# ============================================================
# DEFAULT VALIDATION SETTINGS
# ============================================================

DEFAULT_LOGRHO_MIN = -16.0
DEFAULT_LOGRHO_MAX = -11.0

DEFAULT_T_MIN = 5.0
DEFAULT_T_MAX = 1.0e4

DEFAULT_N_RANDOM = 50000
DEFAULT_SEED = 123456

# Suggested acceptance thresholds.
TOL_MEDIAN = 1.0e-3
TOL_P95 = 5.0e-3
TOL_P99 = 1.0e-2

# The maximum is reported but is intentionally not the primary PASS criterion,
# because very sharp opacity transitions may generate isolated larger errors.
WARN_MAX = 5.0e-2

TRANSITION_T = np.array(
    [
        100.0,
        125.0,
        275.0,
        425.0,
        680.0,
        1000.0,
        1200.0,
        1400.0,
        1500.0,
        1600.0,
    ],
    dtype=np.float64,
)


# ============================================================
# HELPERS
# ============================================================

def header(title):
    print()
    print("=" * 80)
    print(title)
    print("=" * 80)


def load_generator_module(path):
    path = Path(path).resolve()

    if not path.exists():
        raise FileNotFoundError(
            f"Generator script not found: {path}"
        )

    spec = importlib.util.spec_from_file_location(
        "generate_semenov_table_module",
        path,
    )

    if spec is None or spec.loader is None:
        raise RuntimeError(
            f"Could not import generator module from {path}"
        )

    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    required = [
        "parse_nrm_h_s_rosseland_coefficients",
        "parse_gop_grids",
        "read_kR_h2001",
        "semenov_rosseland",
    ]

    missing = [
        name for name in required
        if not hasattr(module, name)
    ]

    if missing:
        raise RuntimeError(
            "Generator module is missing required functions: "
            + ", ".join(missing)
        )

    return module


def load_dense_table(path):
    path = Path(path)

    if not path.exists():
        raise FileNotFoundError(
            f"Dense table not found: {path}"
        )

    with np.load(path, allow_pickle=False) as data:
        logrho = np.asarray(
            data["logrho"],
            dtype=np.float64,
        )

        logT = np.asarray(
            data["logT"],
            dtype=np.float64,
        )

        logkappa = np.asarray(
            data["logkappa"],
            dtype=np.float64,
        )

    if logkappa.shape != (logrho.size, logT.size):
        raise ValueError(
            "Unexpected logkappa shape: "
            f"{logkappa.shape}; expected "
            f"({logrho.size}, {logT.size})"
        )

    if not np.all(np.diff(logrho) > 0.0):
        raise ValueError("logrho grid must be strictly increasing.")

    if not np.all(np.diff(logT) > 0.0):
        raise ValueError("logT grid must be strictly increasing.")

    if not np.all(np.isfinite(logkappa)):
        raise ValueError("Dense table contains non-finite logkappa values.")

    return logrho, logT, logkappa


def bilinear_log_interpolation(
    query_logrho,
    query_logT,
    table_logrho,
    table_logT,
    table_logkappa,
):
    """
    Bilinear interpolation in:

        x = log10(rho)
        y = log10(T)
        z = log10(kappa_R)

    Query points must lie inside the dense table.
    """
    x = np.asarray(
        query_logrho,
        dtype=np.float64,
    )

    y = np.asarray(
        query_logT,
        dtype=np.float64,
    )

    if x.shape != y.shape:
        raise ValueError(
            "query_logrho and query_logT must have identical shapes."
        )

    if (
        np.any(x < table_logrho[0])
        or np.any(x > table_logrho[-1])
        or np.any(y < table_logT[0])
        or np.any(y > table_logT[-1])
    ):
        raise ValueError(
            "At least one query point lies outside the dense table."
        )

    ix = np.searchsorted(
        table_logrho,
        x,
        side="right",
    ) - 1

    iy = np.searchsorted(
        table_logT,
        y,
        side="right",
    ) - 1

    # Clamp points exactly on the upper boundary to the final cell.
    ix = np.clip(
        ix,
        0,
        table_logrho.size - 2,
    )

    iy = np.clip(
        iy,
        0,
        table_logT.size - 2,
    )

    x0 = table_logrho[ix]
    x1 = table_logrho[ix + 1]

    y0 = table_logT[iy]
    y1 = table_logT[iy + 1]

    wx = (x - x0) / (x1 - x0)
    wy = (y - y0) / (y1 - y0)

    z00 = table_logkappa[ix, iy]
    z10 = table_logkappa[ix + 1, iy]
    z01 = table_logkappa[ix, iy + 1]
    z11 = table_logkappa[ix + 1, iy + 1]

    z = (
        (1.0 - wx) * (1.0 - wy) * z00
        + wx * (1.0 - wy) * z10
        + (1.0 - wx) * wy * z01
        + wx * wy * z11
    )

    return z


def direct_opacity_array(
    rho,
    T,
    generator,
    dust_coeff,
    gas_rho_grid,
    gas_T_grid,
    eG,
):
    """
    Evaluate the direct Python reproduction of Semenov at arbitrary points.
    """
    result = np.empty(
        rho.size,
        dtype=np.float64,
    )

    for i in range(rho.size):
        result[i] = generator.semenov_rosseland(
            float(rho[i]),
            float(T[i]),
            dust_coeff,
            gas_rho_grid,
            gas_T_grid,
            eG,
        )

    return result


def compute_error_statistics(k_direct, k_interp):
    valid = (
        np.isfinite(k_direct)
        & np.isfinite(k_interp)
        & (k_direct > 0.0)
        & (k_interp > 0.0)
    )

    if not np.all(valid):
        nbad = np.count_nonzero(~valid)
        raise RuntimeError(
            f"{nbad} validation points produced invalid opacity."
        )

    rel = (
        k_interp - k_direct
    ) / k_direct

    absrel = np.abs(rel)

    logerr = (
        np.log10(k_interp)
        - np.log10(k_direct)
    )

    return {
        "rel": rel,
        "absrel": absrel,
        "logerr": logerr,
        "median": np.median(absrel),
        "p90": np.percentile(absrel, 90.0),
        "p95": np.percentile(absrel, 95.0),
        "p99": np.percentile(absrel, 99.0),
        "p999": np.percentile(absrel, 99.9),
        "maximum": np.max(absrel),
        "mean": np.mean(absrel),
        "rms": np.sqrt(np.mean(rel**2)),
        "max_log": np.max(np.abs(logerr)),
    }


def make_random_points(
    logrho_min,
    logrho_max,
    T_min,
    T_max,
    n,
    seed,
):
    rng = np.random.default_rng(seed)

    logrho = rng.uniform(
        logrho_min,
        logrho_max,
        n,
    )

    logT = rng.uniform(
        np.log10(T_min),
        np.log10(T_max),
        n,
    )

    rho = 10.0**logrho
    T = 10.0**logT

    return logrho, logT, rho, T


def make_transition_points(
    logrho_min,
    logrho_max,
    T_min,
    T_max,
    n_rho=200,
):
    """
    Add deliberately difficult samples around expected opacity transitions.
    This does not replace the random test; it complements it.
    """
    logrho_axis = np.linspace(
        logrho_min,
        logrho_max,
        n_rho,
    )

    logrho_list = []
    T_list = []

    # Sample each nominal transition at offsets ranging from 0.1% to 5%.
    fractional_offsets = np.array(
        [
            -0.05,
            -0.02,
            -0.01,
            -0.005,
            -0.001,
            0.0,
            0.001,
            0.005,
            0.01,
            0.02,
            0.05,
        ],
        dtype=np.float64,
    )

    for T0 in TRANSITION_T:
        for frac in fractional_offsets:
            Tq = T0 * (1.0 + frac)

            if Tq < T_min or Tq > T_max:
                continue

            logrho_list.append(logrho_axis)
            T_list.append(
                np.full_like(
                    logrho_axis,
                    Tq,
                )
            )

    if not logrho_list:
        return (
            np.empty(0),
            np.empty(0),
            np.empty(0),
            np.empty(0),
        )

    logrho = np.concatenate(logrho_list)
    T = np.concatenate(T_list)

    logT = np.log10(T)
    rho = 10.0**logrho

    return logrho, logT, rho, T


def print_stats(label, stats):
    print()
    print(label)
    print("-" * len(label))
    print(
        "mean |relative error|   =",
        f"{stats['mean']:.12e}",
    )
    print(
        "median |relative error| =",
        f"{stats['median']:.12e}",
    )
    print(
        "P90 |relative error|    =",
        f"{stats['p90']:.12e}",
    )
    print(
        "P95 |relative error|    =",
        f"{stats['p95']:.12e}",
    )
    print(
        "P99 |relative error|    =",
        f"{stats['p99']:.12e}",
    )
    print(
        "P99.9 |relative error|  =",
        f"{stats['p999']:.12e}",
    )
    print(
        "max |relative error|    =",
        f"{stats['maximum']:.12e}",
    )
    print(
        "RMS relative error      =",
        f"{stats['rms']:.12e}",
    )
    print(
        "max |Delta log10 kappa| =",
        f"{stats['max_log']:.12e}",
    )


# ============================================================
# MAIN
# ============================================================

def main():
    parser = argparse.ArgumentParser(
        description=(
            "Validate a dense Semenov Rosseland opacity table "
            "against the direct Python COP reproduction."
        )
    )

    parser.add_argument(
        "--generator",
        type=Path,
        default=Path("generate_semenov_table.py"),
        help="Path to generate_semenov_table.py.",
    )

    parser.add_argument(
        "--opacity-f",
        type=Path,
        default=Path("opacity.f"),
        help="Path to original Semenov opacity.f.",
    )

    parser.add_argument(
        "--gas-table",
        type=Path,
        default=Path("kR_h2001.dat"),
        help="Path to original Semenov kR_h2001.dat.",
    )

    parser.add_argument(
        "--table",
        type=Path,
        default=Path("semenov_rosseland_nrm_h_s.npz"),
        help="Dense NPZ table generated previously.",
    )

    parser.add_argument(
        "--logrho-min",
        type=float,
        default=DEFAULT_LOGRHO_MIN,
        help="Minimum log10(rho[g cm^-3]) for validation points.",
    )

    parser.add_argument(
        "--logrho-max",
        type=float,
        default=DEFAULT_LOGRHO_MAX,
        help="Maximum log10(rho[g cm^-3]) for validation points.",
    )

    parser.add_argument(
        "--T-min",
        type=float,
        default=DEFAULT_T_MIN,
        help="Minimum validation temperature [K].",
    )

    parser.add_argument(
        "--T-max",
        type=float,
        default=DEFAULT_T_MAX,
        help="Maximum validation temperature [K].",
    )

    parser.add_argument(
        "--n-random",
        type=int,
        default=DEFAULT_N_RANDOM,
        help="Number of random off-grid validation points.",
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=DEFAULT_SEED,
        help="Random seed.",
    )

    parser.add_argument(
        "--output-prefix",
        type=Path,
        default=Path("semenov_table_validation"),
        help="Prefix for generated validation outputs.",
    )

    args = parser.parse_args()

    header("SEMENOV DENSE-TABLE INTERPOLATION VALIDATION")

    # --------------------------------------------------------
    # Load dense table
    # --------------------------------------------------------

    table_logrho, table_logT, table_logkappa = load_dense_table(
        args.table
    )

    print()
    print("Dense table:")
    print(" file        =", args.table)
    print(" shape       =", table_logkappa.shape)
    print(
        " logrho      =",
        table_logrho[0],
        "...",
        table_logrho[-1],
    )
    print(
        " logT        =",
        table_logT[0],
        "...",
        table_logT[-1],
    )
    print(
        " T range     =",
        10.0**table_logT[0],
        "...",
        10.0**table_logT[-1],
        "K",
    )

    # --------------------------------------------------------
    # Ensure validation domain lies inside dense table
    # --------------------------------------------------------

    if args.logrho_min < table_logrho[0]:
        raise ValueError(
            "Validation logrho_min lies below dense-table coverage."
        )

    if args.logrho_max > table_logrho[-1]:
        raise ValueError(
            "Validation logrho_max lies above dense-table coverage."
        )

    if np.log10(args.T_min) < table_logT[0]:
        raise ValueError(
            "Validation T_min lies below dense-table coverage."
        )

    if np.log10(args.T_max) > table_logT[-1]:
        raise ValueError(
            "Validation T_max lies above dense-table coverage."
        )

    # --------------------------------------------------------
    # Load direct Semenov evaluator
    # --------------------------------------------------------

    generator = load_generator_module(
        args.generator
    )

    dust_coeff = (
        generator.parse_nrm_h_s_rosseland_coefficients(
            args.opacity_f
        )
    )

    gas_rho_grid, gas_T_grid = (
        generator.parse_gop_grids(
            args.opacity_f
        )
    )

    _, eG = generator.read_kR_h2001(
        args.gas_table
    )

    print()
    print("Direct evaluator:")
    print(" generator     =", args.generator)
    print(" opacity.f     =", args.opacity_f)
    print(" gas table     =", args.gas_table)

    # ========================================================
    # RANDOM OFF-GRID TEST
    # ========================================================

    header("RANDOM OFF-GRID TEST")

    (
        logrho_random,
        logT_random,
        rho_random,
        T_random,
    ) = make_random_points(
        args.logrho_min,
        args.logrho_max,
        args.T_min,
        args.T_max,
        args.n_random,
        args.seed,
    )

    print()
    print("N random points =", args.n_random)
    print(
        "logrho range    =",
        args.logrho_min,
        "...",
        args.logrho_max,
    )
    print(
        "T range         =",
        args.T_min,
        "...",
        args.T_max,
        "K",
    )

    k_direct_random = direct_opacity_array(
        rho_random,
        T_random,
        generator,
        dust_coeff,
        gas_rho_grid,
        gas_T_grid,
        eG,
    )

    logk_interp_random = bilinear_log_interpolation(
        logrho_random,
        logT_random,
        table_logrho,
        table_logT,
        table_logkappa,
    )

    k_interp_random = 10.0**logk_interp_random

    random_stats = compute_error_statistics(
        k_direct_random,
        k_interp_random,
    )

    print_stats(
        "Random-point interpolation error",
        random_stats,
    )

    # ========================================================
    # TRANSITION-FOCUSED TEST
    # ========================================================

    header("TRANSITION-FOCUSED TEST")

    (
        logrho_trans,
        logT_trans,
        rho_trans,
        T_trans,
    ) = make_transition_points(
        args.logrho_min,
        args.logrho_max,
        args.T_min,
        args.T_max,
    )

    print()
    print(
        "N transition-focused points =",
        rho_trans.size,
    )

    k_direct_trans = direct_opacity_array(
        rho_trans,
        T_trans,
        generator,
        dust_coeff,
        gas_rho_grid,
        gas_T_grid,
        eG,
    )

    logk_interp_trans = bilinear_log_interpolation(
        logrho_trans,
        logT_trans,
        table_logrho,
        table_logT,
        table_logkappa,
    )

    k_interp_trans = 10.0**logk_interp_trans

    transition_stats = compute_error_statistics(
        k_direct_trans,
        k_interp_trans,
    )

    print_stats(
        "Transition-focused interpolation error",
        transition_stats,
    )

    # --------------------------------------------------------
    # Locate worst random point
    # --------------------------------------------------------

    iworst = np.argmax(
        random_stats["absrel"]
    )

    print()
    print("Worst random point:")
    print(
        " log10 rho      =",
        f"{logrho_random[iworst]:.12e}",
    )
    print(
        " rho            =",
        f"{rho_random[iworst]:.12e}",
        "g cm^-3",
    )
    print(
        " T              =",
        f"{T_random[iworst]:.12e}",
        "K",
    )
    print(
        " kappa direct   =",
        f"{k_direct_random[iworst]:.12e}",
        "cm^2 g^-1",
    )
    print(
        " kappa interp   =",
        f"{k_interp_random[iworst]:.12e}",
        "cm^2 g^-1",
    )
    print(
        " relative error =",
        f"{random_stats['rel'][iworst]:.12e}",
    )

    # ========================================================
    # PASS CRITERIA
    # ========================================================

    PASS_RANDOM = (
        random_stats["median"] < TOL_MEDIAN
        and random_stats["p95"] < TOL_P95
        and random_stats["p99"] < TOL_P99
    )

    PASS_TRANSITION = (
        transition_stats["median"] < TOL_MEDIAN
        and transition_stats["p95"] < TOL_P95
        and transition_stats["p99"] < TOL_P99
    )

    PASS = (
        PASS_RANDOM
        and PASS_TRANSITION
    )

    header("VALIDATION RESULT")

    print(
        "Random interpolation     :",
        "PASS" if PASS_RANDOM else "CHECK REQUIRED",
    )

    print(
        "Transition interpolation :",
        "PASS" if PASS_TRANSITION else "CHECK REQUIRED",
    )

    if random_stats["maximum"] > WARN_MAX:
        print(
            "WARNING: random maximum error exceeds",
            WARN_MAX,
        )

    if transition_stats["maximum"] > WARN_MAX:
        print(
            "WARNING: transition maximum error exceeds",
            WARN_MAX,
        )

    print()
    print(
        "SEMENOV DENSE TABLE VALIDATION:",
        "PASS" if PASS else "CHECK REQUIRED",
    )

    # ========================================================
    # SAVE NUMERICAL RESULTS
    # ========================================================

    np.savez_compressed(
        args.output_prefix.with_suffix(".npz"),
        random_logrho=logrho_random,
        random_logT=logT_random,
        random_rho=rho_random,
        random_T=T_random,
        random_k_direct=k_direct_random,
        random_k_interp=k_interp_random,
        random_rel_error=random_stats["rel"],
        transition_logrho=logrho_trans,
        transition_logT=logT_trans,
        transition_rho=rho_trans,
        transition_T=T_trans,
        transition_k_direct=k_direct_trans,
        transition_k_interp=k_interp_trans,
        transition_rel_error=transition_stats["rel"],
    )

    # ========================================================
    # FIGURE 1: ERROR DISTRIBUTION
    # ========================================================

    fig, ax = plt.subplots(
        1,
        2,
        figsize=(12, 4.8),
    )

    random_positive = np.maximum(
        random_stats["absrel"],
        1e-16,
    )

    trans_positive = np.maximum(
        transition_stats["absrel"],
        1e-16,
    )

    ax[0].hist(
        np.log10(random_positive),
        bins=100,
    )

    ax[0].set_xlabel(
        r"$\log_{10}|\Delta\kappa_R/\kappa_R|$"
    )
    ax[0].set_ylabel("Number of points")
    ax[0].set_title("Random off-grid points")
    ax[0].grid(alpha=0.25)

    ax[1].hist(
        np.log10(trans_positive),
        bins=100,
    )

    ax[1].set_xlabel(
        r"$\log_{10}|\Delta\kappa_R/\kappa_R|$"
    )
    ax[1].set_ylabel("Number of points")
    ax[1].set_title("Transition-focused points")
    ax[1].grid(alpha=0.25)

    plt.tight_layout()

    fig_hist = (
        args.output_prefix.parent
        / f"fig_{args.output_prefix.name}_hist.png"
    )

    plt.savefig(
        fig_hist,
        dpi=200,
        bbox_inches="tight",
    )

    plt.close(fig)

    # ========================================================
    # FIGURE 2: ERROR IN THERMODYNAMIC SPACE
    # ========================================================

    fig, ax = plt.subplots(
        figsize=(8.3, 5.8)
    )

    sc = ax.scatter(
        logT_random,
        logrho_random,
        c=np.log10(random_positive),
        s=6,
        alpha=0.7,
    )

    cbar = fig.colorbar(
        sc,
        ax=ax,
    )

    cbar.set_label(
        r"$\log_{10}|\Delta\kappa_R/\kappa_R|$"
    )

    ax.set_xlabel(
        r"$\log_{10}T\ [{\rm K}]$"
    )

    ax.set_ylabel(
        r"$\log_{10}\rho\ [{\rm g\,cm^{-3}}]$"
    )

    ax.set_title(
        "Semenov dense-table interpolation error"
    )

    plt.tight_layout()

    fig_map = (
        args.output_prefix.parent
        / f"fig_{args.output_prefix.name}_map.png"
    )

    plt.savefig(
        fig_map,
        dpi=200,
        bbox_inches="tight",
    )

    plt.close(fig)

    # ========================================================
    # FIGURE 3: DIRECT VS INTERPOLATED
    # ========================================================

    fig, ax = plt.subplots(
        figsize=(6.5, 6.0)
    )

    ax.loglog(
        k_direct_random,
        k_interp_random,
        ".",
        markersize=2,
        alpha=0.5,
    )

    kmin = min(
        np.min(k_direct_random),
        np.min(k_interp_random),
    )

    kmax = max(
        np.max(k_direct_random),
        np.max(k_interp_random),
    )

    ax.loglog(
        [kmin, kmax],
        [kmin, kmax],
        "--",
        linewidth=1.0,
    )

    ax.set_xlabel(
        r"Direct $\kappa_R\ [{\rm cm^2\,g^{-1}}]$"
    )

    ax.set_ylabel(
        r"Interpolated $\kappa_R\ [{\rm cm^2\,g^{-1}}]$"
    )

    ax.set_title(
        "Direct Semenov vs dense-table interpolation"
    )

    ax.grid(alpha=0.25)

    plt.tight_layout()

    fig_compare = (
        args.output_prefix.parent
        / f"fig_{args.output_prefix.name}_comparison.png"
    )

    plt.savefig(
        fig_compare,
        dpi=200,
        bbox_inches="tight",
    )

    plt.close(fig)

    print()
    print("Written:")
    print(
        " ",
        args.output_prefix.with_suffix(".npz"),
    )
    print(" ", fig_hist)
    print(" ", fig_map)
    print(" ", fig_compare)

    print()
    print("=" * 80)


if __name__ == "__main__":
    main()
