#include "fargo3d.h"

#ifdef RADIATION

/*
 * Temporary FLD diagnostic parameters.
 *
 * These are code-unit test values only. They do not yet represent
 * the physical opacity or speed of light of the final RHD model.
 */
#ifndef RADFLD_KAPPA_TEST
#define RADFLD_KAPPA_TEST 1.0
#endif

#ifndef RADFLD_CLIGHT_TEST
#define RADFLD_CLIGHT_TEST 1.0
#endif

/*
 * Manufactured variable-D test parameters.
 *
 * E_R(r) = A r^2
 * D(r)   = D0 r
 *
 * Exact spherical operator:
 *
 * div(D grad E_R) = 8 A D0 r.
 */
#ifndef RADFLD_VAR_AMP
#define RADFLD_VAR_AMP 1.0
#endif

#ifndef RADFLD_VAR_D0
#define RADFLD_VAR_D0 1.0e-4
#endif

#ifndef RADFLD_VAR_DT
#define RADFLD_VAR_DT 1.0e-3
#endif

/*
 * The two operator tests are mutually exclusive.
 */
#if defined(RADFLDVARTEST) && defined(RADFLDOPTEST)
#error "RADFLDVARTEST and RADFLDOPTEST cannot be enabled simultaneously."
#endif


real RadiationDiffusionDt(real diffcoef) {
  int i,j,k;
  real dx,dy,dz,rate;
  real ratemax_local=0.0;
  real ratemax_global=0.0;

  if (diffcoef <= 0.0)
    return 1e30;

#ifdef Z
  for (k=NGHZ;k<Nz+NGHZ;k++) {
#else
  k=0;
#endif

#ifdef Y
    for (j=NGHY;j<Ny+NGHY;j++) {
#else
    j=0;
#endif

#ifdef X
      for (i=NGHX;i<Nx+NGHX;i++) {
#else
      i=0;
#endif

        rate=0.0;

#ifdef X
        dx=zone_size_x(i,j,k);

        if (dx > 0.0)
          rate+=1.0/(dx*dx);
#endif

#ifdef Y
        dy=zone_size_y(j,k);

        if (dy > 0.0)
          rate+=1.0/(dy*dy);
#endif

#ifdef Z
        dz=zone_size_z(j,k);

        if (dz > 0.0)
          rate+=1.0/(dz*dz);
#endif

        rate*=diffcoef;

        if (rate > ratemax_local)
          ratemax_local=rate;

#ifdef X
      }
#endif

#ifdef Y
    }
#endif

#ifdef Z
  }
#endif

#ifdef PARALLEL

#ifdef FLOAT
  MPI_Allreduce(
    &ratemax_local,
    &ratemax_global,
    1,
    MPI_FLOAT,
    MPI_MAX,
    MPI_COMM_WORLD
  );
#else
  MPI_Allreduce(
    &ratemax_local,
    &ratemax_global,
    1,
    MPI_DOUBLE,
    MPI_MAX,
    MPI_COMM_WORLD
  );
#endif

#else
  ratemax_global=ratemax_local;
#endif

  if (ratemax_global <= 0.0)
    return 1e30;

  /*
   * Explicit diffusion safety factor.
   */
  return 0.20/ratemax_global;
}


void RadiationDiffusion(real dt) {
  int n,nsub,gas_index=-1;
  real dtdiff,dtsub;

  if (dt <= 0.0)
    return;

#ifndef RADFLDVARTEST
  /*
   * The standard constant-D paths require RADDIFFCOEF.
   * The manufactured variable-D test uses RADFLD_VAR_D0 instead.
   */
  if (RADDIFFCOEF <= 0.0)
    return;
#endif

  /*
   * Locate the gas fluid explicitly.
   *
   * MULTIFLUID() leaves FluidIndex=NFLUIDS after completion, so
   * FluidIndex must be restored before FillGhosts/boundary calls.
   */
  for (n=0;n<NFLUIDS;n++) {
    if (Fluids[n]->Fluidtype == GAS) {
      gas_index=n;
      break;
    }
  }

  if (gas_index < 0)
    prs_error("Radiation diffusion requires a gas fluid.");

  FluidIndex=gas_index;
  SelectFluid(FluidIndex);


#ifdef RADFLDVARTEST

  /*
   * Manufactured variable-D operator test.
   *
   * E_R(r) = A r^2
   * D(r)   = D0 r
   *
   * For spherical symmetry:
   *
   * div(D grad E_R)
   *
   * = 1/r^2 d/dr [r^2 D(r) dE_R/dr]
   *
   * = 8 A D0 r.
   *
   * RadiationSetVariableTest initializes both Energyrad and RadDiff
   * over the complete local mesh, including ghost cells. This allows
   * the spatial operator to be tested independently from MPI exchange
   * and physical boundary conditions.
   */
  FARGO_SAFE(
    RadiationSetVariableTest(
      RADFLD_VAR_AMP,
      RADFLD_VAR_D0,
      Energyrad,
      RadDiff
    )
  );

  /*
   * Apply exactly one explicit operator step:
   *
   * E_R,new = E_R + dt_test div(D grad E_R).
   */
  FARGO_SAFE(
    RadiationDiffusionFLDStep(
      RADFLD_VAR_DT,
      Energyrad,
      RadDiff,
      EnergyradNew
    )
  );

  /*
   * Copy the active updated state back to Energyrad.
   *
   * EnergyradNew ghost cells are not generated by the diffusion
   * kernel. They are not used in the manufactured-test measurement,
   * and RadiationSetVariableTest reconstructs the analytical ghost
   * profiles on every subsequent call.
   */
  FARGO_SAFE(
    copy_field(
      Energyrad,
      EnergyradNew
    )
  );

  return;

#endif


  /*
   * Constant-D timestep.
   *
   * This remains valid for:
   *
   * 1. the original constant-D diffusion solver;
   * 2. RADFLDOPTEST, where RadDiff is explicitly forced to
   *    RADDIFFCOEF everywhere.
   */
  dtdiff=RadiationDiffusionDt(RADDIFFCOEF);

  nsub=(int)ceil(dt/dtdiff);

  if (nsub < 1)
    nsub=1;

  dtsub=dt/(real)nsub;


  for (n=0;n<nsub;n++) {

    /*
     * Energyrad and Density require valid halo values before
     * gradients or diagnostic FLD quantities are evaluated.
     */
    FARGO_SAFE(
      FillGhosts(
        PrimitiveVariables()
      )
    );


#ifdef RADFLDOPTEST

    /*
     * Constant-D regression of the new conservative operator.
     *
     * Force:
     *
     * D(x) = RADDIFFCOEF
     *
     * over the complete local array, including ghost cells.
     *
     * Under this condition:
     *
     * div(D grad E_R) = D laplacian(E_R),
     *
     * so RadiationDiffusionFLDStep must reproduce the previously
     * validated RadiationDiffusionStep to floating-point roundoff.
     */
    FARGO_SAFE(
      RadiationSetDiffConstant(
        RADDIFFCOEF,
        RadDiff
      )
    );

    FARGO_SAFE(
      RadiationDiffusionFLDStep(
        dtsub,
        Energyrad,
        RadDiff,
        EnergyradNew
      )
    );


#else

    /*
     * Standard diagnostic FLD path.
     *
     * Compute:
     *
     * R = |grad E_R|/(rho kappa_R E_R)
     *
     * lambda = (2+R)/(6+3R+R^2)
     *
     * D_FLD = c lambda/(rho kappa_R)
     *
     * RadDiff remains diagnostic only in this branch.
     */
    FARGO_SAFE(
      RadiationFLDFields(
        RADFLD_KAPPA_TEST,
        RADFLD_CLIGHT_TEST,
        Energyrad,
        Density,
        RadR,
        RadLambda,
        RadDiff
      )
    );

    /*
     * Previously validated constant-D radiation diffusion update.
     */
    FARGO_SAFE(
      RadiationDiffusionStep(
        dtsub,
        RADDIFFCOEF,
        Energyrad,
        EnergyradNew
      )
    );

#endif


    FARGO_SAFE(
      copy_field(
        Energyrad,
        EnergyradNew
      )
    );
  }


  /*
   * Synchronize the final radiation and gas primitive state.
   */
  FARGO_SAFE(
    FillGhosts(
      PrimitiveVariables()
    )
  );


  /*
   * Recompute R, lambda and D_FLD from the final radiation state.
   *
   * This ensures that diagnostic outputs correspond to the same
   * Energyrad state written to disk.
   */
  FARGO_SAFE(
    RadiationFLDFields(
      RADFLD_KAPPA_TEST,
      RADFLD_CLIGHT_TEST,
      Energyrad,
      Density,
      RadR,
      RadLambda,
      RadDiff
    )
  );


#ifdef RADFLDOPTEST

  /*
   * During RADFLDOPTEST the coefficient actually used by the
   * diffusion operator is RADDIFFCOEF, not the diagnostic D_FLD
   * computed immediately above.
   *
   * Restore RadDiff to the coefficient used by the regression so
   * raddiff*.dat records the actual evolved diffusion coefficient.
   *
   * RadR and RadLambda remain valid diagnostics of the final
   * radiation state.
   */
  FARGO_SAFE(
    RadiationSetDiffConstant(
      RADDIFFCOEF,
      RadDiff
    )
  );

#endif
}

#endif